name: Local CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: my-cicd-app

jobs:
  test:
    runs-on: ubuntu-20.04  # Use supported Ubuntu version
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest app/test_main.py -v

  build-and-push:
    needs: test
    runs-on: ubuntu-20.04  # Use supported Ubuntu version
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      run: |
        docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-20.04  # Use supported Ubuntu version
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.6.0
      with:
        # CORRECTED: Use proper input names (with spaces)
        'minikube version': 'v1.24.0'
        'kubernetes version': 'v1.22.3'
        driver: 'docker'

    - name: Deploy to Minikube
      run: |
        # Load the Docker image into Minikube
        minikube image load ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
        
        # Create deployment
        kubectl create deployment $IMAGE_NAME --image=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
        
        # Expose service
        kubectl expose deployment $IMAGE_NAME --type=NodePort --port=8000
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/$IMAGE_NAME
        
        # Get the Minikube IP and service URL
        echo "Application deployed at:"
        minikube service $IMAGE_NAME --url