name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: my-cicd-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest app/test_main.py -v

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME .

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      run: |
        docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

  deploy-ready:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deployment Ready Notification
      run: |
        echo "🎉 CI/CD Pipeline Completed Successfully!"
        echo "📦 Docker Image: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest"
        echo "✅ Image pushed to Docker Hub and ready for deployment"
        echo ""
        echo "To deploy locally:"
        echo "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest"
        echo "docker run -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest"
        
        echo "To deploy with Docker Compose:"
        echo "docker-compose up -d"
        
        echo "To deploy to Minikube:"
        echo "minikube start"
        echo "minikube image load ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest"
        echo "kubectl create deployment my-app --image=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest"
        echo "kubectl expose deployment my-app --type=NodePort --port=8000"